### ISSUE TITLE
Video example?

### ISSUE THREAD

**Issue by void4** [laserallan/malloc_geiger#4]
This is a great idea :) Would you mind creating a video example for those who don't have Windows but want to see it in action?

Edit: Not a general solution, but I managed to use Python's tracing functionality and the mido library to output MIDI when a function is entered or exited: https://github.com/void4/tonetrace :)
[tracemalloc](https://docs.python.org/3/library/tracemalloc.html) may be another library that could be used.

**Comment by laserallan** [comment]
Thanks, that might be a better way of doing it. I just used what I used last time.
Added a video in README.md so you can see it in action

**Comment by void4** [comment]
Thanks!
