### ISSUE TITLE
VS2019 missing include <memory>

### ISSUE THREAD

**Issue by jamesmagnus** [laserallan/malloc_geiger#6]
Compile error in Visual Studio 2019 because `#include<memory>` is missing in malloc_geiger.cpp.

`malloc_geiger.cpp(71,10): error C2039:  'shared_ptr': is not a member of 'std'`

**Comment by laserallan** [comment]
Thanks, will try to fix it soon!

**Comment by laserallan** [comment]
Fixed now. Thanks for reporting it.
